version: '3.8'

services:
  webtest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - aspnetcoreapp-network

  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE_DATABASE=itemsDB.sqlite
    networks:
      - aspnetcoreapp-network
      
networks:
  aspnetcoreapp-network:
    driver: bridge