version: '3.8'

services:
  webtest:
    container_name: 'webtest'
    image: webtest:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    environment:
      - SQLITE_DATABASE=itemsDB.sqlite
